### ISSUE TITLE
Thanks for the flakes but how did you made your terminal prompt aware of the nix shell

### ISSUE THREAD

**Issue by osbm** [kemalmao19/devShell#1]
Talking about this:

![image](https://github.com/user-attachments/assets/663493ee-3adf-4b68-89a2-6248a0de213b)

**Comment by kemalmao19** [comment]
hi @osbm , u can install starship 
here's their website https://starship.rs/

**Comment by osbm** [comment]
Thank you so much i also have installed starship. It is awesome. 

But it doesn't detect the nix-shell if i run something like this:
```
$ nix shell nixpkgs/4ae2e647537bcdbb82265469442713d066675275#python313
```

But i guess this is because there is not a standartized way to detect if we are inside a nix shell or not. But idk tho

Anyway thank you so much. i am closing this issue :heart:
